export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_TASKS = "SET_TASKS";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";